name: AppEngine
version: 0.0.1
description: A simple App Engine application.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.5.0 <2.0.0'

dependencies:
  appengine: '>=0.3.0 <0.4.0'
